name: tip

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '36 9 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: cleanup
        run: |
          sudo rm -fr /opt/hostedtoolcache/go /usr/local/go /usr/bin/go /bin/go
      - name: install
        run: |
          curl -o go.tar.gz -L \
            https://github.com/AlekSi/golang-tip/releases/download/tip/master.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go.tar.gz
          sudo ln -s /usr/local/go/bin/* /usr/local/bin/
      - uses: actions/checkout@v3

      - name: Get Go environment
        id: go-env
        run: |
          echo "::set-output name=modcache::$(go env GOMODCACHE)"

      - name: Set up mode cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.go-env.outputs.modcache }}
          key: tip-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            tip-${{ runner.os }}-go-

      - name: partial tip test
        # NB: go test ./... fails with
        # github.com/rogpeppe/go-internal/testscript
#        /go/pkg/mod/github.com/rogpeppe/go-internal@v1.8.0/testscript/exe.go:231:51: not enough arguments in call to testing.MainStart
#          have (nopTestDeps, nil, nil, nil)
#          want (testing.testDeps, []testing.InternalTest, []testing.InternalBenchmark, []testing.InternalFuzzTarget, []testing.InternalExample
        run: go test ./fileid/ ./internal/... ./telegram/...
